/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 planet.gltf 
Author: dnslv (https://sketchfab.com/deny.s.trevisan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/alien-planet-bbb2e0eeb0b34247b8a70655c780fad5
Title: Alien Planet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/planet.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Planet} scale={1.2}/>
      <mesh geometry={nodes.Object_6.geometry} material={materials.Clouds} scale={1.27} />
      {/* <mesh geometry={nodes.Object_6.geometry} material={materials.Clouds} scale={1.025} /> */}
    </group>
  )
}

useGLTF.preload('/planet.gltf')
