import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/providers/AuthProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Providers from "@/providers/providers";
// import useLocalStorage from "@/hooks/use-local-storage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const [font, setFont] = useLocalStorage("novel__font", "Default");
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Navbar />
        <main className="px-10">
          <Providers session={session}>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
